## Explore Covid-Moonshot/F@H data

In [23]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [18]:
pd.options.display.max_rows = 20
cols_of_interest = ["SMILES", "canonical_CID", "r_avg_IC50", "f_avg_IC50", "trypsin_IC50"]
activity_data = pd.read_csv("input_data/activity_data.csv", usecols=cols_of_interest)
activity_data

,SMILES,canonical_CID,r_avg_IC50,f_avg_IC50,trypsin_IC50
0,COc1ccc(N(Cc2ccccc2)C(=O)Cc2c[nH]c3ccccc23)cc1,ALP-POS-a3de0cb1-15,NaN,99.500000,NaN
1,CC(=O)N1CCN(CC(=O)Nc2cncc3ccccc23)CC1,ALP-POS-6747fa38-1,NaN,99.500000,NaN
2,COC(=O)C(C(=O)Nc1cnccc1C)c1cccc(Cl)c1,MAT-POS-1e5f28a7-1,17.091397,23.712295,NaN
3,O=C(Cc1cccc(Cl)c1)Nc1cncc2ccncc12,MAT-POS-f7918075-5,2.130501,4.273264,NaN
4,Cc1ccncc1NC(=O)Cc1cc(Cl)cc(-c2ccc(C3CC3(F)F)cc...,MAT-POS-f42f3716-1,NaN,8.438846,NaN
...,...,...,...,...,...
1065,O=C(Nc1cccnc1)Nc1cncc(Cl)c1,DAR-DIA-23aa0b97-15,NaN,NaN,NaN
1066,N#Cc1cncc(CC(=O)Nc2cccnc2)c1,DAR-DIA-23aa0b97-17,NaN,NaN,NaN
1067,N#Cc1cccc(NC(=O)Cc2cncc3ccccc23)c1,DAR-DIA-23aa0b97-19,14.641091,26.680129,NaN
1068,O=C(Cc1cncc2ccccc12)Nc1ccccc1,DAR-DIA-23aa0b97-20,45.077469,57.469670,99.0
1069,CS(=O)(=O)Cc1ccc(C(=O)Nc2cccnc2)o1,ANT-DIA-3c79be55-4,NaN,NaN,NaN

In [36]:
#Compute pIC50 as rapidfire, else fluorescence, else trypsin, else nan:
pIC50s = []

for idx, row in activity_data.iterrows():
    r_ic50 = row[2]
    f_ic50 = row[3]
    t_ic50 = row[4]
    
    if not row.isna()["r_avg_IC50"]:
        pIC50 = r_ic50
    elif not row.isna()["f_avg_IC50"]:
        pIC50 = f_ic50
    elif not row.isna()["trypsin_IC50"]:
        pIC50 = t_ic50
    else:
        pIC50 = False
    if pIC50:
        pIC50s.append([row[0], pIC50])

print(len(pIC50s))

356